FROM ckan/ckan-dev:2.11

USER root
RUN mkdir /srv/app/.local && chown ckan /srv/app/.local

# Install any extensions needed by your CKAN instance
# - Make sure to add the plugins to CKAN__PLUGINS in the .env file
# - Also make sure all provide all extra configuration options, either by:
#   * Adding them to the .env file (check the ckanext-envvars syntax for env vars), or
#   * Adding extra configuration scripts to /docker-entrypoint.d folder) to update
#      the CKAN config file (ckan.ini) with the `ckan config-tool` command
#
# See README > Extending the base images for more details
#
# For instance:
#
### XLoader ###
#RUN pip3 install -e 'git+https://github.com/ckan/ckanext-xloader.git@master#egg=ckanext-xloader' && \ 
#    pip3 install -r ${APP_DIR}/src/ckanext-xloader/requirements.txt && \
#    pip3 install -U requests[security]

### Harvester ###
#RUN pip3 install -e 'git+https://github.com/ckan/ckanext-harvest.git@master#egg=ckanext-harvest' && \
#    pip3 install -r ${APP_DIR}/src/ckanext-harvest/pip-requirements.txt
# will also require gather_consumer and fetch_consumer processes running (please see https://github.com/ckan/ckanext-harvest)

### Scheming ###
#RUN  pip3 install -e 'git+https://github.com/ckan/ckanext-scheming.git@master#egg=ckanext-scheming'

### Pages ###
#RUN  pip3 install -e git+https://github.com/ckan/ckanext-pages.git#egg=ckanext-pages

### DCAT ###
#RUN  pip3 install -e git+https://github.com/ckan/ckanext-dcat.git@v0.0.6#egg=ckanext-dcat && \
#     pip3 install -r https://raw.githubusercontent.com/ckan/ckanext-dcat/v0.0.6/requirements.txt

# Clone the extension(s) your are writing for your own project in the `src` folder
# to get them mounted in this image at runtime

#RUN pip3 install -e 'git+https://github.com/ckan/ckanext-scheming.git@master#egg=ckanext-scheming'
RUN pip3 install setuptools --upgrade && \
    pip3 install -r https://raw.githubusercontent.com/shubham-mahajan/ckanext-s3filestore/feature/r2support-ckan-2.11/requirements.txt && \
    pip3 install --no-cache-dir -e git+https://github.com/shubham-mahajan/ckanext-s3filestore.git@feature/r2support-ckan-2.11#egg=ckanext-s3filestore && \
    pip3 install --no-cache-dir -e git+https://github.com/ckan/ckanext-geoview.git@v0.2.2#egg=ckanext-geoview && \
    pip3 install --no-cache-dir -e git+https://github.com/datopian/ckanext-updatetracking.git@57ec27e2384a07f4ca6189d54e3ef0a8d204e025#egg=ckanext-updatetracking && \
    pip3 install --no-cache-dir -r https://raw.githubusercontent.com/datopian/ckanext-updatetracking/ckan-2.11/requirements.txt && \
    pip3 install --no-cache-dir -e git+https://github.com/ckan/ckanext-pdfview.git@95fe59f0d63bb076a9c9b0ffff5a64c0524d5509#egg=ckanext-pdfview && \
    pip3 install --no-cache-dir -e git+https://github.com/ckan/ckanext-fluent.git@4e9340a934050e937bed49e6009d0971d880410a#egg=ckanext-fluent && \
    pip3 install --no-cache-dir -r https://raw.githubusercontent.com/ckan/ckanext-fluent/4e9340a934050e937bed49e6009d0971d880410a/requirements.txt && \
    pip3 install --no-cache-dir -e git+https://github.com/ckan/ckanext-scheming.git@49527ec191254a2f457b44daf870ca08e9c1a1ea#egg=ckanext-scheming && \
    pip3 install --no-cache-dir -e git+https://github.com/datopian/ckanext-noanonaccess.git@v2.0.4#egg=ckanext-noanonaccess && \
    pip3 install --no-cache-dir -e git+https://github.com/datopian/ckanext-sentry.git@2.10#egg=ckanext-sentry && \
    pip3 install --no-cache-dir -r https://raw.githubusercontent.com/datopian/ckanext-sentry/2.10/requirements.txt && \
    pip3 install --no-cache-dir -e git+https://github.com/datopian/ckanext-translate.git@upgrade/ckan-2.11#egg=ckanext-translate && \
    pip3 install --no-cache-dir -r https://raw.githubusercontent.com/datopian/ckanext-translate/upgrade/ckan-2.11/requirements.txt && \
    pip3 install --no-cache-dir -e git+https://github.com/datopian/ckanext-dcat.git@f9cd1022eeb1ff4c4e65b7d7bab9d674e25117d4#egg=ckanext-dcat && \
    pip3 install --no-cache-dir -r https://raw.githubusercontent.com/datopian/ckanext-dcat/f9cd1022eeb1ff4c4e65b7d7bab9d674e25117d4/requirements.txt && \
    pip3 install --no-cache-dir -e git+https://github.com/ckan/ckanext-harvest.git@v1.6.1#egg=ckanext-harvest && \
    pip3 install --no-cache-dir -r https://raw.githubusercontent.com/ckan/ckanext-harvest/v1.6.1/requirements.txt && \
    pip3 install --no-cache-dir -e git+https://github.com/datopian/ckanext-cprvalidation.git@ckan-v2.11#egg=ckanext-cprvalidation && \
    pip3 install --no-cache-dir -r https://raw.githubusercontent.com/datopian/ckanext-cprvalidation/ckan-v2.11/requirements.txt

# Copy custom initialization scripts
COPY --chown=ckan-sys:ckan-sys docker-entrypoint.d/* /docker-entrypoint.d/

# Apply any patches needed to CKAN core or any of the built extensions (not the
# runtime mounted ones)
COPY --chown=ckan-sys:ckan-sys patches ${APP_DIR}/patches

RUN for d in $APP_DIR/patches/*; do \
        if [ -d $d ]; then \
            for f in `ls $d/*.patch | sort -g`; do \
                cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
            done ; \
        fi ; \
    done
